version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: one-to-one-chat-spring-boot-web-socket-main
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
  mongo-express:
    image: mongo-express
    container_name: one-to-one-chat-spring-boot-web-socket-main
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}